[main]
font=JetBrainsMono Nerd Font Propo:size=16
prompt="  "
icons-enabled=no
show-actions=no

terminal=kitty
width=35
lines=10

horizontal-pad=15
vertical-pad=15
inner-pad=15 

fields=name,generic
filter-desktop=yes

[colors]
background=303446ff
text=c6d0f5ff
match=81c8beff
selection=414559ff
selection-text=c6d0f5ff
selection-match=81c8beff
border=babbf1ff
; NORD color theme
; background=2e3440ff
; text=d8dee9ff
; match=88c0d0ff
; selection=434c5eff
; selection-text=eceff4ff
; selection-match=88c0d0ff
; border=81a1c1ff

[border]
width=2
radius=0
