[main]
font=JetBrainsMono Nerd Font Propo:size=16
prompt="  "
icons-enabled=no
show-actions=no

terminal=kitty
width=35
lines=10

horizontal-pad=15
vertical-pad=15
inner-pad=15 

fields=name,generic
filter-desktop=yes

[colors]
background=000000ff
text=ffffffff
match=550000ff
selection=2a0000ff
selection-text=ffffffff
selection-match=ff0000ff
border=550000ff

; NORD color theme
; background=2e3440ff
; text=d8dee9ff
; match=88c0d0ff
; selection=434c5eff
; selection-text=eceff4ff
; selection-match=88c0d0ff
; border=81a1c1ff

[border]
width=2
radius=0
