input {
  kb_layout = ee
    kb_variant = us
    kb_model =
    kb_options =

    # focus follow cursor
    follow_mouse = 1

    accel_profile = flat
    force_no_accel = false
    sensitivity = 0.5
}
